# Generated by Django 5.2.3 on 2025-06-20 10:30

import apps.user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(help_text='Password must be at least 8 characters long and contain an uppercase letter, a lowercase letter, a number, and a special character.', max_length=128, validators=[apps.user.models.validate_strong_password]),
        ),
    ]
