# Generated by Django 5.2.3 on 2025-07-21 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_scholar',
            field=models.BooleanField(default=False, help_text='Designates whether the user is a scholar.'),
        ),
    ]
