# Generated by Django 5.2.3 on 2025-06-16 19:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessToken', models.TextField()),
                ('refreashToken', models.TextField()),
                ('ip', models.GenericIPAddressField(protocol='IPv4')),
                ('userAgent', models.TextField()),
                ('fid', models.CharField(max_length=50)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('expiresAt', models.DateTimeField()),
                ('refreshTokenExpiresAt', models.DateTimeField()),
                ('isLoggedIn', models.BooleanField(default=True)),
                ('logoutTime', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_session', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
