# Generated by Django 5.2.3 on 2025-07-21 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='remember_me',
            field=models.BooleanField(default=False),
        ),
    ]
